/**
 * @input  依赖：SessionConfig 类型、环境变量映射、TOML 字符转义
 * @output 导出：Codex config.toml 生成器（clipods 标记、API 会话默认协作特性注入）
 * @pos    会话配置到 Codex CLI 配置的转换层（含转义与 feature 冲突规避）
 *
 * ⚠️ 一旦本文件被更新，务必更新以上注释
 */
import type { SessionConfig } from "../types/config";

const getEnvValue = (
  env: Record<string, string> | undefined,
  key: string
): string => (env?.[key] ?? "").trim();

const escapeTomlString = (value: string): string =>
  value
    .replace(/\\/gu, "\\\\")
    .replace(/"/gu, "\\\"")
    .replace(/\n/gu, "\\n")
    .replace(/\r/gu, "\\r")
    .replace(/\t/gu, "\\t");

const toTomlString = (value: string): string => `"${escapeTomlString(value)}"`;

const hasFeatureConfig = (extra: string): boolean => {
  if (!extra.trim()) {
    return false;
  }
  if (/(^|\n)\s*\[features\]\s*(\n|$)/u.test(extra)) {
    return true;
  }
  return /(^|\n)\s*features\.[A-Za-z0-9_-]+\s*=/u.test(extra);
};

const buildEnvHttpHeaders = (env: Record<string, string>): string | null => {
  const org = getEnvValue(env, "OPENAI_ORGANIZATION");
  const project = getEnvValue(env, "OPENAI_PROJECT");
  const entries: string[] = [];
  if (org) {
    entries.push(`"OpenAI-Organization" = "OPENAI_ORGANIZATION"`);
  }
  if (project) {
    entries.push(`"OpenAI-Project" = "OPENAI_PROJECT"`);
  }
  if (!entries.length) {
    return null;
  }
  return `{ ${entries.join(", ")} }`;
};

export const buildCodexConfig = (session: SessionConfig): string => {
  const extra = session.extraConfigToml ?? "";
  const lines: string[] = [
    "# Generated by clipods",
    "# Only include the minimal keys needed for this session.",
    "",
  ];

  if (session.loginType === "api") {
    lines.push('forced_login_method = "api"');
  } else {
    lines.push('forced_login_method = "chatgpt"');
  }

  const env = session.env ?? {};
  const model = getEnvValue(env, "OPENAI_MODEL");
  if (model) {
    lines.push(`model = ${toTomlString(model)}`);
  }

  const baseUrl = getEnvValue(env, "OPENAI_BASE_URL");
  const useCustomProvider = session.loginType === "api" && Boolean(baseUrl);
  if (useCustomProvider) {
    lines.push('model_provider = "custom"');
    lines.push("");
    lines.push("[model_providers.custom]");
    lines.push('name = "custom"');
    lines.push('wire_api = "responses"');
    lines.push("requires_openai_auth = false");
    lines.push(`base_url = ${toTomlString(baseUrl)}`);
  } else {
    lines.push('model_provider = "openai"');
    const envHeaders = buildEnvHttpHeaders(env);
    const needsProviderBlock =
      Boolean(baseUrl) || Boolean(envHeaders) || session.loginType === "api";

    if (needsProviderBlock) {
      lines.push("");
      lines.push("[model_providers.openai]");
      lines.push('name = "openai"');
      if (baseUrl) {
        lines.push(`base_url = ${toTomlString(baseUrl)}`);
      }
      if (session.loginType === "api") {
        lines.push('env_key = "OPENAI_API_KEY"');
      }
      if (envHeaders) {
        lines.push(`env_http_headers = ${envHeaders}`);
      }
    }
  }

  if (session.loginType === "api" && !hasFeatureConfig(extra)) {
    lines.push("");
    lines.push("[features]");
    lines.push("collab = true");
    lines.push("collaboration_modes = true");
    lines.push("unified_exec = true");
    lines.push("shell_snapshot = true");
    lines.push("steer = true");
  }

  if (extra.trim()) {
    lines.push("");
    lines.push("# --- extra config (appended) ---");
    lines.push(extra.trim());
  }

  lines.push("");
  return lines.join("\n");
};
